export const list = [
  {
    id: 'manryeokgimyo-seungjachongtong',
    명칭: '「만력기묘」명 승자총통',
    형태: '원기둥형',
    재질: '금속',
    시대: '조선',
    용도: '군사',
    image: '「만력기묘」명 승자총통_메인.jpg',
    description:
      '병부에 새겨진 명문을 통해 만력 기묘년(1579년, 선조 12)에 규가(揆加)라는 장인이 만든 총통임을 알 수 있...거리를 개선한 휴대용 화약 무기이다. 『화포식언해』를 통해 탄환과 화살이 모두 사용 가능한 총통임을 알 수 있다.',
    recommended_items: [
      { name: '먹통', image: '먹통_01.jpg' },
      { name: '탄환', image: '탄환_02.jpg' },
      { name: '철제은상감총', image: '철제은상감총鐵製銀象嵌銃_03.jpg' },
    ],
    related_projects: [{ name: '하늘이 내린 재상, 류성룡', image: '하늘이 내린 재상, 류성룡.png' }],
  },
  {
    id: 'hwangbichangcheon-mirror',
    명칭: '「황비창천」을 새긴 거울',
    형태: '원형',
    재질: '금속',
    시대: '고려',
    용도: '주생활',
    image: '황비창천을 새긴 거울_메인.jpg',
    description: '신선 세계를 찾아가는 배가 새겨진 고려 시대 팔각형 거울로, 당대의 신앙적 요소가 반영되어 있다.',
    recommended_items: [
      { name: '청동 거울(왕비)', image: '청동 거울왕비_01.jpg' },
      { name: '꽃 동물무늬 붙인 옻칠 거울', image: '꽃 동물무늬 붙인 옻칠 거울_02.jpg' },
      { name: '거란의 글씨가 새겨있는 거울', image: '거란의 글씨가 새겨있는 거울_03.jpg' },
    ],
    related_projects: [{ name: '국립중앙박물관 중·근세관', image: '중근세관_고려1실.jpg' }],
  },
  {
    id: 'gyeongguk-daejeon',
    명칭: '경국대전',
    형태: '사각형',
    재질: '종이',
    시대: '조선',
    용도: '사회생활',
    image: '경국대전_메인.jpg',
    description:
      '조선왕조의 기본 법전으로, 세조의 명으로 편찬을 시작하여 1485년(성종16) 성종 대에 완성되었다. 조선 초기 《경제육전(經濟六典)》과 그 뒤의 법령을 종합하여 여러 차례 개정을 거쳐 만들었다. 조선의 통치체제는 《경국대전》을 바탕으로 정비되었다.',
    recommended_items: [
      { name: '암행어사 보고서', image: '암행어사 보고서_01.jpg' },
      { name: '오시복 교지', image: '오시복 교지_02.jpg' },
      {
        name: '이항복이 쓴 백사선생수서제병진적첩',
        image: '이항복이 쓴 백사선생수서제병진적첩_03.jpg',
      },
    ],
    related_projects: [{ name: '국립중앙박물관 중·근세관', image: '중근세관_고려1실.jpg' }],
  },
  {
    id: 'geumgwan',
    명칭: '금관',
    형태: '기하학형',
    재질: '금속',
    시대: '신라',
    용도: '의생활',
    image: '',
    description:
      '신라 금관은 둥그런 테의 정면 위에 출자형 입식(出字形立飾)을 세우고, 그 좌우로 나뭇가지형 장식을 배치한 형태가 특징적이다. 화려한 금제 드리개가 달려 의례용 머리 장식품으로 쓰였다.',
    recommended_items: [
      { name: '경주 서봉총 출토 금제 허리띠', image: '' },
      { name: '금제 드리개', image: '' },
      { name: '경주 부부총 금귀걸이', image: '' },
    ],
    related_projects: [
      {
        name: '국립중앙박물관 조각·공예관 > 금속공예실, 과학으로 풀어 보는 서봉총 금관',
        image: '',
      },
    ],
  },
  {
    id: 'geumdong-amita-buljasang',
    명칭: '금동 아미타불 좌상',
    형태: '인물형',
    재질: '금속',
    시대: '고려',
    용도: '종교신앙',
    image: '',
    description: '고려 시대 금동(금박)으로 만들어진 아미타불 좌상이다.',
    recommended_items: [
      { name: '금동관음보살좌상', image: '' },
      { name: '금동불좌상·금동보살입상', image: '' },
      { name: '동제아미타불좌상', image: '' },
    ],
    related_projects: [{ name: '대고려 918·2018 그 찬란한 도전', image: '' }],
  },
  {
    id: 'naseon-saseumppul-pianambi',
    명칭: '나선 사슴뿔을 표현한 피아남비',
    형태: '기하학형',
    재질: '흙',
    시대: '철기시대',
    용도: '주생활',
    image: '',
    description: '울산 달천리에서 출토된 청동기~철기 과도기 토기. 나선형으로 표현된 사슴뿔 장식이 특징적이다.',
    recommended_items: [
      { name: '청동낫', image: '' },
      { name: '청동기 방울', image: '' },
      { name: '청동제환두파형도', image: '' },
    ],
    related_projects: [{ name: '선사·고대관 1실 청동기 전시', image: '' }],
  },
  {
    id: 'daedong-yeojido',
    명칭: '대동여지도',
    형태: '두루마리형',
    재질: '종이',
    시대: '조선',
    용도: '과학기술',
    image: '',
    description: '김정호가 제작한 조선 후기 전국 지도로, 축척을 통일하고 도로망을 상세히 표기한 실용적 대형 지도이다.',
    recommended_items: [
      { name: '동국지도', image: '' },
      { name: '지승지도', image: '' },
      { name: '팔도총도', image: '' },
    ],
    related_projects: [{ name: '지도, 세상을 그리다', image: '' }],
  },
  {
    id: 'dojagi-mandeuldon-saramdeul',
    명칭: '도자기 만들던 사람들',
    형태: '입체형',
    재질: '도토',
    시대: '조선',
    용도: '생산도구',
    image: '',
    description: '도자기 제작 과정을 보여주는 모형(또는 도상)으로, 조선 시대 도자 생산 공정 이해에 도움을 준다.',
    recommended_items: [
      { name: '분원 가마 도구', image: '' },
      { name: '백자소성잔편', image: '' },
      { name: '도자 제작 삽입물', image: '' },
    ],
    related_projects: [{ name: '분원백자 특별전', image: '' }],
  },
  {
    id: 'dolkal',
    명칭: '돌칼',
    형태: '직선형',
    재질: '돌',
    시대: '청동기시대',
    용도: '생산도구',
    image: '',
    description: '곡물 수확 등에 사용된 것으로 추정되는 청동기 시대 석제 농공구.',
    recommended_items: [
      { name: '돌낫', image: '' },
      { name: '돌화살촉', image: '' },
      { name: '돌괭이', image: '' },
    ],
    related_projects: [{ name: '선사농경문화 전시', image: '' }],
  },
  {
    id: 'donggwe',
    명칭: '동궤',
    형태: '사각형',
    재질: '금속',
    시대: '조선',
    용도: '주생활',
    image: '',
    description: '의복이나 귀중품을 보관하던 청동제 궤짝. 금속면 장식과 자물쇠 구조가 특징.',
    recommended_items: [
      { name: '나전칠기궤', image: '' },
      { name: '목제상자(잠금장치)', image: '' },
      { name: '금구 장석 세트', image: '' },
    ],
    related_projects: [{ name: '조선 주거생활실', image: '' }],
  },
  {
    id: 'manwoldae-baekja',
    명칭: '만월대 건물지 출토 백자',
    형태: '사발형',
    재질: '도토',
    시대: '고려',
    용도: '주생활',
    image: '',
    description: '개성 만월대 궁궐 터에서 출토된 고려 백자. 궁중용 식기로 사용된 것으로 보인다.',
    recommended_items: [
      { name: '청자상감운학문매병', image: '' },
      { name: '백자대접', image: '' },
      { name: '분청사기편', image: '' },
    ],
    related_projects: [{ name: '고려도자 특별전', image: '' }],
  },
  {
    id: 'mokgwan',
    명칭: '목관',
    형태: '사각형',
    재질: '나무',
    시대: '고대',
    용도: '장례',
    image: '',
    description: '목재로 제작된 관. 매장 풍습과 장례 의례 연구에 중요한 자료.',
    recommended_items: [
      { name: '석곽 구조 모형', image: '' },
      { name: '부장품 토기 세트', image: '' },
      { name: '청동장식 관못', image: '' },
    ],
    related_projects: [{ name: '고대 장례문화실', image: '' }],
  },
  {
    id: 'bangasayusang',
    명칭: '반가사유상',
    형태: '인물형',
    재질: '금속',
    시대: '삼국시대',
    용도: '종교신앙',
    image: '',
    description:
      '한 발을 다른 무릎 위에 올리고 손가락을 뺨에 댄 사유 자세의 보살상. 한국 불교 조각을 대표하는 걸작 이미지.',
    recommended_items: [
      { name: '금동미륵보살반가사유상(다른본)', image: '' },
      { name: '석조보살좌상', image: '' },
      { name: '불두 파편', image: '' },
    ],
    related_projects: [{ name: '불교조각 명품전', image: '' }],
  },
  {
    id: 'boksik-jaehyeonpum-joseon-gungjung',
    명칭: '복식 재현품(조선 궁중)',
    형태: '의복형',
    재질: '직물',
    시대: '조선',
    용도: '의생활',
    image: '',
    description: '조선 궁중 복식을 고증해 재현한 전시용 의복 세트.',
    recommended_items: [
      { name: '활옷', image: '' },
      { name: '곤룡포', image: '' },
      { name: '대례복 장신구', image: '' },
    ],
    related_projects: [{ name: '조선 궁중문화 특별전', image: '' }],
  },
  {
    id: 'saseumppul-jeonsi-jiwon-jeonsi',
    명칭: '사슴뿔전시지원전시',
    형태: '기타',
    재질: '기타',
    시대: '기타',
    용도: '기타',
    image: '',
    description: '사슴뿔 관련 전시 지원 자료.',
    recommended_items: [
      { name: '사슴뼈', image: '' },
      { name: '사슴상 토우', image: '' },
      { name: '사슴문양 직물', image: '' },
    ],
    related_projects: [{ name: '사슴과 인간 전시', image: '' }],
  },
  {
    id: 'sarijangeomgu',
    명칭: '사리장엄구',
    형태: '입체형',
    재질: '금속',
    시대: '통일신라',
    용도: '종교신앙',
    image: '',
    description: '부처의 사리를 봉안하기 위해 제작된 장엄구 세트.',
    recommended_items: [
      { name: '사리기', image: '' },
      { name: '금제장식판', image: '' },
      { name: '청동합', image: '' },
    ],
    related_projects: [{ name: '사리장엄 특별전', image: '' }],
  },
  {
    id: 'seokgeom',
    명칭: '석검',
    형태: '직선형',
    재질: '돌',
    시대: '청동기시대',
    용도: '의례',
    image: '',
    description: '청동검 형태를 모방해 만든 석제 의례용 무기.',
    recommended_items: [
      { name: '석창', image: '' },
      { name: '비파형동검', image: '' },
      { name: '동검주형', image: '' },
    ],
    related_projects: [{ name: '선사무기 전시', image: '' }],
  },
  {
    id: 'seokgwanmyo-bujangpum',
    명칭: '석관묘 부장품',
    형태: '묘역형',
    재질: '혼합',
    시대: '청동기시대',
    용도: '장례',
    image: '',
    description: '석관묘에서 함께 출토된 토기·석기 세트.',
    recommended_items: [
      { name: '석관 모형', image: '' },
      { name: '부장 토기', image: '' },
      { name: '장신구편', image: '' },
    ],
    related_projects: [{ name: '선사 장례문화실', image: '' }],
  },
  {
    id: 'seokjo-yeorae-jasang',
    명칭: '석조여래좌상',
    형태: '인물형',
    재질: '돌',
    시대: '고려',
    용도: '종교신앙',
    image: '',
    description: '석재로 조성된 여래좌상. 온화한 미소와 간결한 옷주름 표현을 보인다.',
    recommended_items: [
      { name: '석탑부재', image: '' },
      { name: '불좌대편', image: '' },
      { name: '광배편', image: '' },
    ],
    related_projects: [{ name: '석불조각 명품전', image: '' }],
  },
  {
    id: 'seokjo-yumul-josa-bogoseo',
    명칭: '석조유물조사보고서',
    형태: '문서형',
    재질: '종이',
    시대: '근현대',
    용도: '기록',
    image: '',
    description: '석조 문화재 조사 기록 문서.',
    recommended_items: [
      { name: '유물측량도', image: '' },
      { name: '보수기록표', image: '' },
      { name: '사진기록집', image: '' },
    ],
    related_projects: [{ name: '문화재 조사연구 아카이브', image: '' }],
  },
  {
    id: 'seokchondong-gobun-jangsingu',
    명칭: '석촌동 고분 출토 장신구',
    형태: '장신구',
    재질: '금속',
    시대: '삼국시대',
    용도: '의생활',
    image: '',
    description: '서울 석촌동 고분군에서 출토된 금속 장신구 세트.',
    recommended_items: [
      { name: '은제장신구', image: '' },
      { name: '옥제구슬', image: '' },
      { name: '금제관식편', image: '' },
    ],
    related_projects: [{ name: '삼국 귀족문화 전시', image: '' }],
  },
  {
    id: 'seongdeokdaewang-sinjong-mohyeong',
    명칭: '성덕대왕신종 모형',
    형태: '종형',
    재질: '금속',
    시대: '통일신라',
    용도: '종교신앙',
    image: '',
    description: '경주 봉덕사 ‘에밀레종’으로 알려진 성덕대왕신종을 축소 재현한 모형.',
    recommended_items: [
      { name: '범종 추금장식', image: '' },
      { name: '범종타편', image: '' },
      { name: '종루 모형', image: '' },
    ],
    related_projects: [{ name: '한국의 범종 전시', image: '' }],
  },
  {
    id: 'sejong-sillok',
    명칭: '세종실록',
    형태: '책형',
    재질: '종이',
    시대: '조선',
    용도: '기록',
    image: '',
    description: '조선 세종 재위 기간을 기록한 실록 권책.',
    recommended_items: [
      { name: '조선왕조실록(총서)', image: '' },
      { name: '승정원일기', image: '' },
      { name: '실록편찬도구', image: '' },
    ],
    related_projects: [{ name: '조선왕조 기록문화 특별전', image: '' }],
  },
  {
    id: 'sorigubsoe',
    명칭: '소리굽쇠',
    형태: 'U자형',
    재질: '금속',
    시대: '근현대',
    용도: '과학기술',
    image: '',
    description: '진동으로 표준음 높이를 내는 튜닝 포크.',
    recommended_items: [
      { name: '피아노조율도구', image: '' },
      { name: '음차세트', image: '' },
      { name: '음향발진기', image: '' },
    ],
    related_projects: [{ name: '소리의 과학 전시', image: '' }],
  },
  {
    id: 'sutgama-mohyeong',
    명칭: '숯가마 모형',
    형태: '입체형',
    재질: '흙',
    시대: '전통',
    용도: '생산도구',
    image: '',
    description: '숯을 굽던 전통 가마 구조를 재현한 모형.',
    recommended_items: [
      { name: '숯덩이', image: '' },
      { name: '목탄제작도구', image: '' },
      { name: '화덕모형', image: '' },
    ],
    related_projects: [{ name: '전통 연료문화 전시', image: '' }],
  },
  {
    id: 'sijeong-ilgi',
    명칭: '시정일기',
    형태: '책형',
    재질: '종이',
    시대: '조선',
    용도: '기록',
    image: '',
    description: '지방 행정 운영 상황을 기록한 문서.',
    recommended_items: [
      { name: '관찰사 보고', image: '' },
      { name: '읍지', image: '' },
      { name: '향안', image: '' },
    ],
    related_projects: [{ name: '조선 지방행정 전시', image: '' }],
  },
  {
    id: 'ssiat-sujangyong-hangari',
    명칭: '씨앗 수장용 항아리',
    형태: '항아리형',
    재질: '흙',
    시대: '선사',
    용도: '생산도구',
    image: '',
    description: '씨앗이나 곡물을 저장하는 데 사용된 토기 항아리.',
    recommended_items: [
      { name: '곡물탄화편', image: '' },
      { name: '저장구덩이 모형', image: '' },
      { name: '토기뚜껑', image: '' },
    ],
    related_projects: [{ name: '선사 농경문화실', image: '' }],
  },
  {
    id: 'arario-dulletogi',
    명칭: '아라리오 둘레토기',
    형태: '토기형',
    재질: '흙',
    시대: '선사',
    용도: '주생활',
    image: '',
    description: '입 둘레 장식이 특징인 선사 토기.',
    recommended_items: [
      { name: '빗살무늬토기', image: '' },
      { name: '덧띠무늬토기', image: '' },
      { name: '굽다리토기', image: '' },
    ],
    related_projects: [{ name: '선사 토기문화 전시', image: '' }],
  },
  {
    id: 'angbu-ilgu',
    명칭: '앙부일구',
    형태: '반구형',
    재질: '금속',
    시대: '조선',
    용도: '과학기술',
    image: '',
    description: '해시계를 반구형 그릇 모양으로 만든 휴대용 시간 측정 기구.',
    recommended_items: [
      { name: '일성정시의', image: '' },
      { name: '천문의기', image: '' },
      { name: '측우기', image: '' },
    ],
    related_projects: [{ name: '조선 과학기술 전시', image: '' }],
  },
  {
    id: 'yeongjo-eopil',
    명칭: '영조어필',
    형태: '문서형',
    재질: '종이',
    시대: '조선',
    용도: '기록',
    image: '',
    description: '조선 영조가 직접 쓴 어필 서예.',
    recommended_items: [
      { name: '정조어필', image: '' },
      { name: '왕실서예첩', image: '' },
      { name: '묵죽도 어필', image: '' },
    ],
    related_projects: [{ name: '왕실서예 특별전', image: '' }],
  },
  {
    id: 'ok-gwigori',
    명칭: '옥귀걸이',
    형태: '장신구',
    재질: '옥/유리',
    시대: '선사',
    용도: '의생활',
    image: '',
    description: '옥으로 만든 귀걸이 장신구.',
    recommended_items: [
      { name: '옥팔찌', image: '' },
      { name: '옥구슬', image: '' },
      { name: '옥목걸이편', image: '' },
    ],
    related_projects: [{ name: '선사 장신구 전시', image: '' }],
  },
  {
    id: 'ongwan',
    명칭: '옹관',
    형태: '원통형',
    재질: '흙',
    시대: '삼국시대',
    용도: '장례',
    image: '',
    description: '유아 또는 소형 매장에 쓰인 대형 토기 항아리형 관.',
    recommended_items: [
      { name: '옹관뚜껑', image: '' },
      { name: '옹관부장토기', image: '' },
      { name: '옹관매장모형', image: '' },
    ],
    related_projects: [{ name: '삼국 장례문화 전시', image: '' }],
  },
  {
    id: 'usan-guk-togi',
    명칭: '우산국 토기',
    형태: '토기형',
    재질: '흙',
    시대: '고대',
    용도: '주생활',
    image: '',
    description: '울릉도 일대 우산국 문화권에서 제작된 토기.',
    recommended_items: [
      { name: '우산국 토우', image: '' },
      { name: '해양교역유물', image: '' },
      { name: '석기편', image: '' },
    ],
    related_projects: [{ name: '해양문화 전시', image: '' }],
  },
  {
    id: 'yuribyeong-gyoyeokpum',
    명칭: '유리병(교역품)',
    형태: '용기형',
    재질: '옥/유리',
    시대: '고대',
    용도: '주생활',
    image: '',
    description: '교역으로 전래된 유리제 용기.',
    recommended_items: [
      { name: '유리구슬', image: '' },
      { name: '유리잔편', image: '' },
      { name: '수입도자', image: '' },
    ],
    related_projects: [{ name: '실크로드 교역 전시', image: '' }],
  },
  {
    id: 'ipsa-kkotmunui-hap',
    명칭: '입사 꽃무늬 합',
    형태: '원통형',
    재질: '금속',
    시대: '조선',
    용도: '주생활',
    image: '',
    description: '금속 표면에 상감 기법으로 꽃무늬를 넣어 장식한 합.',
    recommended_items: [
      { name: '입사문합(소형)', image: '' },
      { name: '은입사동합', image: '' },
      { name: '칠보장식합', image: '' },
    ],
    related_projects: [{ name: '조선 공예 전시', image: '' }],
  },
  {
    id: 'jagigi',
    명칭: '자기기',
    형태: '기타',
    재질: '도토',
    시대: '조선',
    용도: '생산도구',
    image: '',
    description: '자기(도자기) 제작 관련 기구를 뜻하는 포괄 항목.',
    recommended_items: [
      { name: '점토혼합기', image: '' },
      { name: '가마받침', image: '' },
      { name: '소성용받침편', image: '' },
    ],
    related_projects: [{ name: '도자기 제작 과정 전시', image: '' }],
  },
  {
    id: 'jeoul',
    명칭: '저울',
    형태: '기구형',
    재질: '금속',
    시대: '근현대',
    용도: '과학기술',
    image: '',
    description: '물건의 무게를 재는 기구.',
    recommended_items: [
      { name: '추세트', image: '' },
      { name: '전자저울(현대)', image: '' },
      { name: '분동', image: '' },
    ],
    related_projects: [{ name: '측정의 역사 전시', image: '' }],
  },
  {
    id: 'jeopsi',
    명칭: '접시',
    형태: '접시형',
    재질: '도토',
    시대: '전통',
    용도: '주생활',
    image: '',
    description: '음식을 담는 평저형 식기.',
    recommended_items: [
      { name: '사발', image: '' },
      { name: '잔', image: '' },
      { name: '뚜껑접시', image: '' },
    ],
    related_projects: [{ name: '한국 식문화 전시', image: '' }],
  },
  {
    id: 'jeongap',
    명칭: '전갑',
    형태: '장비형',
    재질: '금속',
    시대: '조선',
    용도: '군사',
    image: '',
    description: '전투에서 몸을 보호하기 위한 갑옷.',
    recommended_items: [
      { name: '투구', image: '' },
      { name: '갑주편', image: '' },
      { name: '병장기', image: '' },
    ],
    related_projects: [{ name: '조선 군사문화 전시', image: '' }],
  },
  {
    id: 'jumeok-dokki',
    명칭: '주먹도끼',
    형태: '타원형',
    재질: '돌',
    시대: '구석기시대',
    용도: '생산도구',
    image: '',
    description: '인류가 사용한 가장 오래된 다목적 석기 도구 중 하나.',
    recommended_items: [
      { name: '긁개', image: '' },
      { name: '찍개', image: '' },
      { name: '슴베찌르개', image: '' },
    ],
    related_projects: [{ name: '구석기 문화관', image: '' }],
  },
  {
    id: 'cheoljae-eunsanggam-chong',
    명칭: '철제은상감총',
    형태: '원기둥형',
    재질: '금속',
    시대: '조선',
    용도: '군사',
    image: '',
    description: '철제 몸체에 은으로 상감 장식한 총통류 무기.',
    recommended_items: [
      { name: '승자총통', image: '' },
      { name: '천자총통', image: '' },
      { name: '각종탄환', image: '' },
    ],
    related_projects: [{ name: '조선 화포 전시', image: '' }],
  },
  {
    id: 'togi-danji',
    명칭: '토기 단지',
    형태: '항아리형',
    재질: '흙',
    시대: '선사',
    용도: '주생활',
    image: '',
    description: '저장용 대형 토기 단지.',
    recommended_items: [
      { name: '토기뚜껑편', image: '' },
      { name: '소형단지', image: '' },
      { name: '토기사발', image: '' },
    ],
    related_projects: [{ name: '선사 저장문화 전시', image: '' }],
  },
  {
    id: 'palman-daejanggyeong-mokpan',
    명칭: '팔만대장경 목판',
    형태: '판형',
    재질: '나무',
    시대: '고려',
    용도: '종교신앙',
    image: '',
    description: '해인사에 보관된 대장경 인경용 목판. 불교 경전 전체를 집대성한 목판 인쇄 문화의 정수.',
    recommended_items: [
      { name: '대장경 인출본', image: '' },
      { name: '인경도구', image: '' },
      { name: '경전보관함', image: '' },
    ],
    related_projects: [{ name: '팔만대장경과 인쇄문화', image: '' }],
  },
  {
    id: 'hwal',
    명칭: '활',
    형태: '곡선형',
    재질: '나무',
    시대: '전통',
    용도: '군사',
    image: '',
    description: '전통 전투 및 사냥용 활.',
    recommended_items: [
      { name: '화살', image: '' },
      { name: '활집', image: '' },
      { name: '각궁제작도구', image: '' },
    ],
    related_projects: [{ name: '한국 활쏘기 문화', image: '' }],
  },
  {
    id: 'haesigye',
    명칭: '해시계',
    형태: '기구형',
    재질: '금속',
    시대: '조선',
    용도: '과학기술',
    image: '',
    description: '태양의 위치로 시간을 측정하는 기구.',
    recommended_items: [
      { name: '휴대해시계', image: '' },
      { name: '자명종', image: '' },
      { name: '천문관측기구', image: '' },
    ],
    related_projects: [{ name: '조선시대 시각 측정 전시', image: '' }],
  },
  {
    id: 'seokgi-hwasalchok',
    명칭: '석기 화살촉',
    형태: '삼각형',
    재질: '돌',
    시대: '신석기시대',
    용도: '사냥',
    image: '',
    description: '사냥용 투사 무기의 석제 촉.',
    recommended_items: [
      { name: '석창촉', image: '' },
      { name: '뼈화살촉', image: '' },
      { name: '사냥도구모형', image: '' },
    ],
    related_projects: [{ name: '신석기 사냥문화 전시', image: '' }],
  },
  {
    id: 'cheongdong-geoul-wangbi',
    명칭: '청동 거울(왕비)',
    형태: '원형',
    재질: '금속',
    시대: '고려',
    용도: '의생활',
    image: '',
    description: '왕비 등 고위층이 사용했을 것으로 추정되는 청동 거울.',
    recommended_items: [
      { name: '거울케이스', image: '' },
      { name: '화장도구세트', image: '' },
      { name: '거울걸이', image: '' },
    ],
    related_projects: [{ name: '궁중생활 전시', image: '' }],
  },
]
